CREATE TABLE IF NOT EXISTS scans (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root_path text NOT NULL,
    scanned_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id integer NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
    relative_path text NOT NULL,
    full_path text NOT NULL,
    parent_relative_path text NULL,
    name text NOT NULL,
    is_directory boolean NOT NULL,
    size_bytes bigint NOT NULL,
    files_count integer NOT NULL,
    CONSTRAINT uq_scan_items_scan_path UNIQUE (scan_id, relative_path)
);

CREATE INDEX IF NOT EXISTS ix_scan_items_scan_id
    ON scan_items (scan_id);

CREATE INDEX IF NOT EXISTS ix_scan_items_parent
    ON scan_items (scan_id, parent_relative_path);

